# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Peachy Theme"
license = "MIT"
licenselink = "https://github.com/kgoedecke/gohugo-theme-peachy/blob/master/LICENSE.md"
description = "Peachy Theme for Hugo"
homepage = "https://github.com/kgoedecke/gohugo-theme-peachy"
tags = ["website", "starter", "responsive", "Disqus", "blog", "Tachyons"]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = 0.0.1

[author]
  name = "Kevin Goedecke"
  homepage = "https://github.com/kgoedecke"
